version: "2"
linters:
  default: none
  enable:
    - staticcheck
    - gocritic
    - gosec
    - govet
    - revive
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
